---
- name: configure sshd service
  lineinfile:
    path: /etc/ssh/sshd_config
    line: GatewayPorts clientspecified
  notify: restart sshd service
  become: yes
- name: check if firewalld is running
  command: systemctl status firewalld
  register: firewalld_status
  changed_when: false
  failed_when: firewalld_status.rc > 4
- name: open firewall ports
  firewalld:
    port: 12200-12209/tcp
    state: enabled
    permanent: yes
    immediate: yes
  when: firewalld_status.rc == 0
  become: yes
