---
- name: Make sure user account exists
  user:
    name: "{{ user }}"
  become: true

- name: "Install client's SSH public key"
  authorized_key:
    user: "{{ user }}"
    key: "{{ item }}"
  with_file:
    - "{{ ssh_public_key_file }}"
  become: true

- name: Configure sshd service for reliable remote port forwarding
  tags: notest
  lineinfile:
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
  with_items:
    - insertafter: "^#GatewayPorts "
      line: GatewayPorts clientspecified
      regexp: "^GatewayPorts "
    - insertafter: "^#ClientAliveInterval "
      line: ClientAliveInterval {{ client_alive_interval }}
      regexp: "^ClientAliveInterval "
    - insertafter: "^ClientAliveCountMax "
      line: ClientAliveCountMax {{ client_alive_count_max }}
      regexp: "^ClientAliveCountMax "
  become: true
  notify: Restart sshd service

- name: Check if firewalld is active
  tags: notest
  command: /usr/bin/systemctl is-active firewalld
  changed_when: false
  check_mode: false
  failed_when: false
  register: firewalld_is_active_results

- name: Open firewall port
  tags: notest
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ firewall_port }}/tcp"
    state: enabled
  become: true
  when:
    - firewalld_is_active_results.rc == 0
    - firewall_port is defined
