---
- name: configure sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: GatewayPorts clientspecified
  notify:
    - restart sshd
- name: open firewall ports
  firewalld:
    port: 12200-12209/tcp
    state: enabled
    permanent: yes
    immediate: yes
