---
- name: Make sure user account exists
  user:
    name: "{{ user }}"
  become: true

- name: "Install client's SSH public key"
  authorized_key:
    user: "{{ user }}"
    key: "{{ item }}"
  with_file:
    - "{{ ssh_public_key_file }}"
  become: true

- name: Configure sshd service for remote port forwarding
  tags: notest
  lineinfile:
    insertafter: "^#GatewayPorts "
    line: GatewayPorts clientspecified
    path: /etc/ssh/sshd_config
  become: true
  notify: Restart sshd service

- name: Check if firewalld is running
  tags: notest
  command: systemctl is-active firewalld
  changed_when: false
  register: firewalld_is_running_results

- name: Open firewall port
  tags: notest
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ firewall_port }}/tcp"
    state: enabled
  become: true
  when:
    - firewalld_is_running_results.rc == 0
    - firewall_port is defined
