---
- name: configure sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    line: GatewayPorts clientspecified
  notify:
    - restart sshd
  become: yes
- name: open firewall ports
  firewalld:
    port: 12200-12209/tcp
    state: enabled
    permanent: yes
    immediate: yes
  become: yes
